Web3Auth/web3auth-android-sdk

app/src/main/java/com/openlogin/app/MainActivity.kt
core/src/main/java/com/openlogin/core/AuthStateChangeListener.kt
core/src/main/java/com/openlogin/core/OpenLogin.kt

This change is required to implement mechanism for subscribing state changes from react native side.

feat: add mechanism for listening to state changes

---

.idea/compiler.xml
.idea/deploymentTargetDropDown.xml
.idea/gradle.xml
.idea/jarRepositories.xml
.idea/misc.xml
README.md
app/build.gradle
app/proguard-rules.pro
app/src/main/AndroidManifest.xml
app/src/main/java/com/openlogin/app/LoginVerifier.kt
app/src/main/java/com/openlogin/app/MainActivity.kt
app/src/main/res/layout/activity_main.xml
app/src/main/res/layout/item_dropdown.xml
build.gradle
core/build.gradle
core/proguard-rules.pro
core/src/main/java/com/openlogin/core/AuthStateChangeListener.kt
core/src/main/java/com/openlogin/core/OpenLogin.kt
core/src/main/java/com/openlogin/core/Utils.kt
core/src/main/java/com/openlogin/core/types/Display.kt
core/src/main/java/com/openlogin/core/types/ExtraLoginOptions.kt
core/src/main/java/com/openlogin/core/types/LoginParams.kt
core/src/main/java/com/openlogin/core/types/OpenLoginOptions.kt
core/src/main/java/com/openlogin/core/types/OpenLoginResponse.kt
core/src/main/java/com/openlogin/core/types/Prompt.kt
core/src/main/java/com/openlogin/core/types/State.kt
core/src/main/java/com/openlogin/core/types/UserCancelledException.kt
core/src/main/java/com/openlogin/core/types/UserInfo.kt
gradle/wrapper/gradle-wrapper.properties

login dropdown and choosing browser

Fd 594 login dropdown and choosing browser

---

app/src/main/java/com/openlogin/app/LoginVerifier.kt
app/src/main/java/com/openlogin/app/MainActivity.kt
core/src/main/java/com/openlogin/core/OpenLogin.kt
core/src/main/java/com/openlogin/core/types/LoginConfigItem.kt
core/src/main/java/com/openlogin/core/types/LoginParams.kt
core/src/main/java/com/openlogin/core/types/OpenLoginOptions.kt
core/src/main/java/com/openlogin/core/types/Provider.kt
core/src/main/java/com/openlogin/core/types/TypeOfLogin.kt

Fix whitelabel
add support for custom verifiers

Add custom verifier support

---

app/build.gradle
core/build.gradle
core/src/main/java/com/web3auth/core/Web3Auth.kt
core/src/main/java/com/web3auth/core/keystore/KeyStoreManagerUtils.kt

Handle changes for shared prefs wrt android version 12 and above

Handle changes for shared prefs wrt android version 12 and above

---

.idea/thriftCompiler.xml
core/src/main/AndroidManifest.xml
core/src/main/java/com/web3auth/core/Utils.kt
core/src/main/java/com/web3auth/core/Web3Auth.kt
core/src/main/java/com/web3auth/core/api/ApiHelper.kt

* Added fallback mechanism when network becomes unstable or not available.

Added fallback mechanism when network becomes unstable or not available

---

app/src/main/java/com/web3auth/app/MainActivity.kt
core/src/main/java/com/web3auth/core/Web3Auth.kt
core/src/main/java/com/web3auth/core/keystore/KeyStoreManagerUtils.kt
core/src/main/java/com/web3auth/core/types/Web3AuthOptions.kt
core/src/main/java/com/web3auth/core/types/Web3AuthResponse.kt

Adding coreKitKey and coreKitEd25519PrivKey in Web3AuthResponse

Adding coreKitKey and coreKitEd25519PrivKey in Web3AuthResponse.kt

---

app/src/main/java/com/web3auth/app/MainActivity.kt
app/src/main/res/values/strings.xml
core/src/main/java/com/web3auth/core/Web3Auth.kt
core/src/main/java/com/web3auth/core/types/Web3AuthError.kt
core/src/main/java/com/web3auth/core/types/Web3AuthResponse.kt

Exposed getUserInfo() method

---

app/src/main/java/com/web3auth/app/MainActivity.kt
core/build.gradle
core/src/main/java/com/web3auth/core/Web3Auth.kt

bump session-manager-android sdk version

bump session-manager-android sdk version

---

core/src/main/java/com/web3auth/core/types/Network.kt

removing celeste network

---

core/build.gradle
core/src/main/java/com/web3auth/core/keystore/KeyStoreManagerUtils.kt

bump library deps

---

app/build.gradle
core/build.gradle

update session-manager-android sdk for obfuscation

Update session manager sdk for obfuscation

---

core/build.gradle
core/proguard-rules.pro
core/src/main/java/com/web3auth/core/keystore/KeyStoreManagerUtils.kt

update session-manager-android sdk and proguard rules for bouncycastle library

update session-manager-android sdk and proguard rules for bouncycastle library

---

core/build.gradle

bump session-managr-android sdk

bump session-managr-android sdk

---

core/src/main/java/com/web3auth/core/Web3Auth.kt

code refactored.

---

core/build.gradle

bump session manager sdk

---

app/src/main/java/com/web3auth/app/MainActivity.kt
core/src/main/java/com/web3auth/core/Web3Auth.kt
core/src/main/java/com/web3auth/core/types/LoginConfigItem.kt

fix: add mfaSettings in initOptions

fix: add mfaSettings in initOptions

---

app/src/main/java/com/web3auth/app/MainActivity.kt
core/src/main/java/com/web3auth/core/Web3Auth.kt
core/src/main/java/com/web3auth/core/types/LoginParams.kt
core/src/main/java/com/web3auth/core/types/Web3AuthOptions.kt

add sessionTime in Web3AuthOptions.kt

add sessionTime in Web3AuthOptions.kt

---

core/src/main/java/com/web3auth/core/types/Web3AuthOptions.kt

feat: update openlogin version to v6

feat: update openlogin version to v6

---

core/build.gradle
core/src/main/java/com/web3auth/core/Web3Auth.kt

feat: update session manager sdk

---

app/src/main/AndroidManifest.xml
core/src/main/AndroidManifest.xml

* Remove theme from manifest file

feat: remove themee from manifest file.

---

core/src/main/java/com/web3auth/core/WebViewActivity.kt

* Webview backpress fucntionality added

feat: webview backpress fucntionality added

---

core/src/main/java/com/web3auth/core/Web3Auth.kt

feat: isAndroid flag added in walletMap

feat: isAndroid flag added in walletMap

---

core/src/main/java/com/web3auth/core/types/Web3AuthOptions.kt

* Update openLoginVersion to v8

feat: update openLoginVersion to v8

---

app/src/main/java/com/web3auth/app/MainActivity.kt
core/src/main/java/com/web3auth/core/WebViewActivity.kt
core/src/main/java/com/web3auth/core/types/ChainConfig.kt

* Hide action bar from Webview and ChainConfig schema updated.

feat: hide action bar from Webview and update ChainConfig schema

---

core/src/main/java/com/web3auth/core/WebViewActivity.kt

* Webview enhancements
https://github.com/Web3Auth/web3auth-android-sdk/assets/44719313/6c513fc2-b2f8-4402-aecb-5f7688a56465

feat: webview enhancements

---

core/src/main/java/com/web3auth/core/Web3Auth.kt
core/src/main/java/com/web3auth/core/types/Web3AuthError.kt

* enableMFA() fucntion enhancements

feat: enableMFA() enhancements

---

app/src/main/AndroidManifest.xml
core/src/main/AndroidManifest.xml

* manifest file enhancements for EncryptedShredPreferences

feat: manifest file enhancements for EncryptedShredPreferences

---

app/src/main/java/com/web3auth/app/MainActivity.kt
core/src/main/java/com/web3auth/core/Web3Auth.kt
core/src/main/java/com/web3auth/core/types/Provider.kt
core/src/main/java/com/web3auth/core/types/Web3AuthOptions.kt

*New Login providers added and launchWalletServices() function updated

feat: add new providers and update launchWalletServices() function

---

core/src/main/java/com/web3auth/core/types/TypeOfLogin.kt

Fixes https://github.com/Web3Auth/web3auth-android-sdk/issues/94

fix: EMAIL_PASSWORDLESS serialized name

---

core/src/main/java/com/web3auth/core/Web3Auth.kt

update getInitParams() and pass appState and dappurl params.

feat: update getInitParams()

---

core/src/main/java/com/web3auth/core/types/TypeOfLogin.kt

feat: update TypeOfLogin

---

core/build.gradle

feat: update session-manager deps

---

README.md

Update README.md to update version

---

core/src/main/java/com/web3auth/core/Web3Auth.kt

* session in request() function
Jira Link: https://toruslabs.atlassian.net/browse/PD-4245
* Problem Statement: Launch Wallet UI -> Close Wallet UI and then launch the Transaction Confirmation Screen, it doesn't work.
Fix: Session in request() function.
* Tested on emulator.
https://github.com/user-attachments/assets/7b189f96-fa13-482e-941d-e3d8530b4d22

bugFix: session in request() function

---

core/src/main/java/com/web3auth/core/Web3Auth.kt

Jira Link: https://toruslabs.atlassian.net/browse/DEVREL-1134?atlOrigin=eyJpIjoiOTIxZjk4NTdhMjYwNGYxMGE3ZDhmNzdkZjBlYjNjNjAiLCJwIjoiaiJ9
Update default session time to 1 day
N/A

Update default sessionTime

---

core/src/main/java/com/web3auth/core/types/Web3AuthOptions.kt

* bump wallet-services version
Jira Link:
* bump wallet-services version
* On Emulator
https://github.com/user-attachments/assets/4c88481d-fe12-4274-97a2-7ef1b8d4c4ad

feat: bump wallet-services version
